version: 2.1
jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
  run-component-tests:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
      - run:
          name: Run Cypress component tests
          command: npx cypress run --component
workflows:
  run-tests:
    jobs:
      - start-server
      - run-component-tests:
          requires:
            - start-server
